<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class XeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('xes')->truncate();
        DB::table('xes')->delete();

        $data = [

            [
                'id_cu_dan' => 1,
                'bien_so_xe' => '30A-00001',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 2,
                'bien_so_xe' => '30A-00002',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 0,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 3,
                'bien_so_xe' => '30A-00003',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 4,
                'bien_so_xe' => '30A-00004',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 1,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 5,
                'bien_so_xe' => '30A-00005',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 0,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 6,
                'bien_so_xe' => '30A-00006',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 1,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 7,
                'bien_so_xe' => '30A-00007',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 8,
                'bien_so_xe' => '30A-00008',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 0,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 9,
                'bien_so_xe' => '30A-00009',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 10,
                'bien_so_xe' => '30A-00010',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 0,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 11,
                'bien_so_xe' => '30A-00011',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 1,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 12,
                'bien_so_xe' => '30A-00012',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 0,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 13,
                'bien_so_xe' => '30A-00013',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 1,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 14,
                'bien_so_xe' => '30A-00014',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 15,
                'bien_so_xe' => '30A-00015',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 0,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 16,
                'bien_so_xe' => '30A-00016',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 17,
                'bien_so_xe' => '30A-00017',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 0,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 18,
                'bien_so_xe' => '30A-00018',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 19,
                'bien_so_xe' => '30A-00019',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 0,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 20,
                'bien_so_xe' => '30A-00020',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 21,
                'bien_so_xe' => '30A-00021',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 0,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 22,
                'bien_so_xe' => '30A-00022',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 23,
                'bien_so_xe' => '30A-00023',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 0,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 24,
                'bien_so_xe' => '30A-00024',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 1,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 25,
                'bien_so_xe' => '30A-00025',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 0,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 26,
                'bien_so_xe' => '30A-00026',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 27,
                'bien_so_xe' => '30A-00027',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 0,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 28,
                'bien_so_xe' => '30A-00028',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 29,
                'bien_so_xe' => '30A-00029',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 1,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 30,
                'bien_so_xe' => '30A-00030',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 0,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 31,
                'bien_so_xe' => '30A-00031',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 0,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 32,
                'bien_so_xe' => '30A-00032',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 33,
                'bien_so_xe' => '30A-00033',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 1,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 34,
                'bien_so_xe' => '30A-00034',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 0,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 35,
                'bien_so_xe' => '30A-00035',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 1,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 36,
                'bien_so_xe' => '30A-00036',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 0,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 37,
                'bien_so_xe' => '30A-00037',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 1,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 38,
                'bien_so_xe' => '30A-00038',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 0,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 39,
                'bien_so_xe' => '30A-00039',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 1,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 40,
                'bien_so_xe' => '30A-00040',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 0,
                'is_con_han' => true,
            ],

            [
                'id_cu_dan' => 41,
                'bien_so_xe' => '30A-00041',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 42,
                'bien_so_xe' => '30A-00042',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 0,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 43,
                'bien_so_xe' => '30A-00043',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 44,
                'bien_so_xe' => '30A-00044',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 0,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 45,
                'bien_so_xe' => '30A-00045',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 1,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 46,
                'bien_so_xe' => '30A-00046',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 0,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 47,
                'bien_so_xe' => '30A-00047',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 1,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 48,
                'bien_so_xe' => '30A-00048',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 49,
                'bien_so_xe' => '30A-00049',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 0,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 50,
                'bien_so_xe' => '30A-00050',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 1,
                'bien_so_xe' => '30A-00051',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 0,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 2,
                'bien_so_xe' => '30A-00052',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 1,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 3,
                'bien_so_xe' => '30A-00053',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 4,
                'bien_so_xe' => '30A-00054',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 0,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 5,
                'bien_so_xe' => '30A-00055',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 0,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 6,
                'bien_so_xe' => '30A-00056',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 1,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 7,
                'bien_so_xe' => '30A-00057',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 8,
                'bien_so_xe' => '30A-00058',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 0,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 9,
                'bien_so_xe' => '30A-00059',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 10,
                'bien_so_xe' => '30A-00060',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 0,
                'is_con_han' => true,
            ],

            [
                'id_cu_dan' => 11,
                'bien_so_xe' => '30A-00061',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 12,
                'bien_so_xe' => '30A-00062',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 0,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 13,
                'bien_so_xe' => '30A-00063',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 14,
                'bien_so_xe' => '30A-00064',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 0,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 15,
                'bien_so_xe' => '30A-00065',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 1,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 16,
                'bien_so_xe' => '30A-00066',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 17,
                'bien_so_xe' => '30A-00067',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 0,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 18,
                'bien_so_xe' => '30A-00068',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 1,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 19,
                'bien_so_xe' => '30A-00069',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 0,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 20,
                'bien_so_xe' => '30A-00070',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 1,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 21,
                'bien_so_xe' => '30A-00071',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 22,
                'bien_so_xe' => '30A-00072',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 0,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 23,
                'bien_so_xe' => '30A-00073',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 24,
                'bien_so_xe' => '30A-00074',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 0,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 25,
                'bien_so_xe' => '30A-00075',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 1,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 26,
                'bien_so_xe' => '30A-00076',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 27,
                'bien_so_xe' => '30A-00077',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 0,
                'is_con_han' => false,
            ],
            [
                'id_cu_dan' => 28,
                'bien_so_xe' => '30A-00078',
                'id_loai_xe' => 3,
                'trang_thai_duyet' => 1,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 29,
                'bien_so_xe' => '30A-00079',
                'id_loai_xe' => 1,
                'trang_thai_duyet' => 0,
                'is_con_han' => true,
            ],
            [
                'id_cu_dan' => 30,
                'bien_so_xe' => '30A-00080',
                'id_loai_xe' => 2,
                'trang_thai_duyet' => 1,
                'is_con_han' => false,
            ],
            [
        'id_cu_dan' => 31,
        'bien_so_xe' => '30A-00081',
        'id_loai_xe' => 3,
        'trang_thai_duyet' => 0,
        'is_con_han' => true,
    ],
    [
        'id_cu_dan' => 32,
        'bien_so_xe' => '30A-00082',
        'id_loai_xe' => 1,
        'trang_thai_duyet' => 1,
        'is_con_han' => false,
    ],
    [
        'id_cu_dan' => 33,
        'bien_so_xe' => '30A-00083',
        'id_loai_xe' => 2,
        'trang_thai_duyet' => 0,
        'is_con_han' => true,
    ],
    [
        'id_cu_dan' => 34,
        'bien_so_xe' => '30A-00084',
        'id_loai_xe' => 3,
        'trang_thai_duyet' => 1,
        'is_con_han' => true,
    ],
    [
        'id_cu_dan' => 35,
        'bien_so_xe' => '30A-00085',
        'id_loai_xe' => 1,
        'trang_thai_duyet' => 1,
        'is_con_han' => false,
    ],
    [
        'id_cu_dan' => 36,
        'bien_so_xe' => '30A-00086',
        'id_loai_xe' => 2,
        'trang_thai_duyet' => 0,
        'is_con_han' => true,
    ],
    [
        'id_cu_dan' => 37,
        'bien_so_xe' => '30A-00087',
        'id_loai_xe' => 3,
        'trang_thai_duyet' => 1,
        'is_con_han' => false,
    ],
    [
        'id_cu_dan' => 38,
        'bien_so_xe' => '30A-00088',
        'id_loai_xe' => 1,
        'trang_thai_duyet' => 0,
        'is_con_han' => true,
    ],
    [
        'id_cu_dan' => 39,
        'bien_so_xe' => '30A-00089',
        'id_loai_xe' => 2,
        'trang_thai_duyet' => 1,
        'is_con_han' => false,
    ],
    [
        'id_cu_dan' => 40,
        'bien_so_xe' => '30A-00090',
        'id_loai_xe' => 3,
        'trang_thai_duyet' => 1,
        'is_con_han' => true,
    ],
    [
        'id_cu_dan' => 41,
        'bien_so_xe' => '30A-00091',
        'id_loai_xe' => 1,
        'trang_thai_duyet' => 1,
        'is_con_han' => false,
    ],
    [
        'id_cu_dan' => 42,
        'bien_so_xe' => '30A-00092',
        'id_loai_xe' => 2,
        'trang_thai_duyet' => 0,
        'is_con_han' => true,
    ],
    [
        'id_cu_dan' => 43,
        'bien_so_xe' => '30A-00093',
        'id_loai_xe' => 3,
        'trang_thai_duyet' => 1,
        'is_con_han' => false,
    ],
    [
        'id_cu_dan' => 44,
        'bien_so_xe' => '30A-00094',
        'id_loai_xe' => 1,
        'trang_thai_duyet' => 0,
        'is_con_han' => true,
    ],
    [
        'id_cu_dan' => 45,
        'bien_so_xe' => '30A-00095',
        'id_loai_xe' => 2,
        'trang_thai_duyet' => 1,
        'is_con_han' => false,
    ],
    [
        'id_cu_dan' => 46,
        'bien_so_xe' => '30A-00096',
        'id_loai_xe' => 3,
        'trang_thai_duyet' => 1,
        'is_con_han' => true,
    ],
    [
        'id_cu_dan' => 47,
        'bien_so_xe' => '30A-00097',
        'id_loai_xe' => 1,
        'trang_thai_duyet' => 0,
        'is_con_han' => true,
    ],
    [
        'id_cu_dan' => 48,
        'bien_so_xe' => '30A-00098',
        'id_loai_xe' => 2,
        'trang_thai_duyet' => 1,
        'is_con_han' => false,
    ],
    [
        'id_cu_dan' => 49,
        'bien_so_xe' => '30A-00099',
        'id_loai_xe' => 3,
        'trang_thai_duyet' => 0,
        'is_con_han' => true,
    ],
    [
        'id_cu_dan' => 50,
        'bien_so_xe' => '30A-00100',
        'id_loai_xe' => 1,
        'trang_thai_duyet' => 1,
        'is_con_han' => true,
    ],

        ];

        DB::table('xes')->insert($data);
    }
}
